"""Added nutrition, calories, time, instructions and ingredients to recipe model

Revision ID: 283170545141
Revises: 85793c875a11
Create Date: 2025-09-23 11:33:53.150067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283170545141'
down_revision = '85793c875a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('calories', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('protein', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('carbs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fats', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipes_user_id_users'), 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipes_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('time')
        batch_op.drop_column('fats')
        batch_op.drop_column('carbs')
        batch_op.drop_column('protein')
        batch_op.drop_column('calories')
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
