"""edit user model

Revision ID: 85793c875a11
Revises: 1ffecba1fbaa
Create Date: 2025-07-30 19:13:33.526139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85793c875a11'
down_revision = '1ffecba1fbaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
